# Generated by Django 4.2.30 on 2026-06-01 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('attendance', '0001_initial'),
        ('timetable', '0001_initial'),
        ('subjects', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_attendance_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='organizations.semester'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='timetable.timetable'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancecorrection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancecorrection',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='attendancecorrection',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancecorrection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['organization', 'date'], name='attendance__organiz_bcab55_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['organization', 'session_status'], name='attendance__organiz_24d0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['organization', 'branch', 'department'], name='attendance__organiz_4f87c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'date', 'hour', 'subject'), name='uniq_active_attendance_session'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['organization', 'status'], name='attendance__organiz_024827_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['organization', 'capture_method'], name='attendance__organiz_75fe8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('session', 'student'), name='uniq_active_attendance_record_per_session_student'),
        ),
    ]
