# Generated by Django 4.2.30 on 2026-06-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='capture_method',
            field=models.CharField(choices=[('FACE_RECOGNITION', 'Face Recognition'), ('MANUAL', 'Manual'), ('SYSTEM', 'System'), ('QR', 'QR'), ('IMPORT', 'Import')], default='MANUAL', max_length=20),
        ),
    ]
