# Generated by Django 4.2.30 on 2026-06-10 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_schema_rbac_hod_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_in_app_channel_and_schedules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationschedule',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameIndex(
            model_name='notificationschedule',
            new_name='notificatio_organiz_a52491_idx',
            old_name='notif_sched_org_active_next_idx',
        ),
        migrations.AlterField(
            model_name='notificationschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notificationschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationschedule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='notificationschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
