# Generated by Django 4.2.30 on 2026-06-03 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_schema_rbac_hod_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('refresh_jti', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('login_method', models.CharField(choices=[('password', 'Password'), ('face', 'Face'), ('token', 'Token')], default='password', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('logged_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'is_active', 'last_seen_at'], name='authenticat_user_id_cf517f_idx'), models.Index(fields=['refresh_jti', 'is_active'], name='authenticat_refresh_634b80_idx'), models.Index(fields=['ip_address', 'created_at'], name='authenticat_ip_addr_33bd5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=120)),
                ('login_method', models.CharField(choices=[('password', 'Password'), ('face', 'Face'), ('token', 'Token')], default='password', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['email', 'success', 'created_at'], name='authenticat_email_2a9d53_idx'), models.Index(fields=['ip_address', 'created_at'], name='authenticat_ip_addr_1dccaa_idx'), models.Index(fields=['user', 'created_at'], name='authenticat_user_id_8191e7_idx')],
            },
        ),
    ]
