# Generated by Django 4.2.30 on 2026-06-10 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_schema_rbac_hod_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0002_studymaterial_material_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studymaterial',
            name='mat_org_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='studymaterial',
            new_name='materials_s_organiz_49e587_idx',
            old_name='materials_st_organiz_2d0775_idx',
        ),
        migrations.RenameIndex(
            model_name='studymaterial',
            new_name='materials_s_organiz_c40391_idx',
            old_name='materials_st_organiz_5a1cc2_idx',
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='material_type',
            field=models.CharField(choices=[('NOTES', 'Notes'), ('ASSIGNMENTS', 'Assignments'), ('SLIDES', 'Slides'), ('VIDEOS', 'Videos')], db_index=True, default='NOTES', max_length=16),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
