from django.urls import path
from .views import (
    CompleteLoginView,
    CreateHODAccountView,
    HODDashboardSummaryView,
    HodPortalContextView,
    FacultyDashboardSummaryView,
    FacultyPortalContextView,
    StudentDashboardSummaryView,
    StudentPortalContextView,
    SuperAdminDashboardSummaryView,
    CustomTokenObtainPairView, 
    RefreshTokenView,
    InitiateLoginView,
    VerifyFaceView,
    UserDetailView,
    LogoutView,
    ForgotPasswordView,
    ResetPasswordView,
    ChangePasswordView,
    SwitchOrganizationView,
)
from .session_views import PasswordPolicyView, UserSessionListView, UserSessionRevokeAllView, UserSessionRevokeView

urlpatterns = [
    path('token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', RefreshTokenView.as_view(), name='token_refresh'),
    path('initiate-login/', InitiateLoginView.as_view(), name='initiate_login'),
    path('verify-face/', VerifyFaceView.as_view(), name='verify_face'),
    path('complete-login/', CompleteLoginView.as_view(), name='complete_login'),
    path('me/', UserDetailView.as_view(), name='user_me'),
    path('switch-organization/', SwitchOrganizationView.as_view(), name='switch_organization'),
    path('logout/', LogoutView.as_view(), name='user_logout'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='user_forgot_password'),
    path('reset-password/', ResetPasswordView.as_view(), name='user_reset_password'),
    path('change-password/', ChangePasswordView.as_view(), name='user_change_password'),
    path('password-policy/', PasswordPolicyView.as_view(), name='password_policy'),
    path('sessions/', UserSessionListView.as_view(), name='user_sessions'),
    path('sessions/revoke-all/', UserSessionRevokeAllView.as_view(), name='user_sessions_revoke_all'),
    path('sessions/<uuid:session_key>/revoke/', UserSessionRevokeView.as_view(), name='user_session_revoke'),
    path('accounts/hod/', CreateHODAccountView.as_view(), name='create_hod_account'),
    path('super-admin/dashboard-summary/', SuperAdminDashboardSummaryView.as_view(), name='super_admin_dashboard_summary'),
    path('hod/dashboard-summary/', HODDashboardSummaryView.as_view(), name='hod_dashboard_summary'),
    path('hod/portal-context/', HodPortalContextView.as_view(), name='hod_portal_context'),
    path('faculty/dashboard-summary/', FacultyDashboardSummaryView.as_view(), name='faculty_dashboard_summary'),
    path('faculty/portal-context/', FacultyPortalContextView.as_view(), name='faculty_portal_context'),
    path('student/dashboard-summary/', StudentDashboardSummaryView.as_view(), name='student_dashboard_summary'),
    path('student/portal-context/', StudentPortalContextView.as_view(), name='student_portal_context'),
]
