# Generated by Django 4.2.30 on 2026-06-10 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_schema_rbac_hod_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='examschedule',
            new_name='exams_exams_organiz_e54fba_idx',
            old_name='exams_exams_organiz_342355_idx',
        ),
        migrations.RenameIndex(
            model_name='examschedule',
            new_name='exams_exams_organiz_58145c_idx',
            old_name='exams_exams_organiz_f2c9f5_idx',
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
