# Generated by Django 4.2.30 on 2026-06-03 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_schema_rbac_hod_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('ATTENDANCE_SUMMARY', 'Attendance Summary'), ('ATTENDANCE_DETAIL', 'Attendance Detail'), ('ATTENDANCE_DEFICIT', 'Attendance Deficit'), ('FACULTY_WORKLOAD', 'Faculty Workload'), ('STUDENT_PERFORMANCE', 'Student Performance'), ('DEPARTMENT_ANALYTICS', 'Department Analytics'), ('EXAM_TIMETABLE', 'Exam Timetable'), ('TIMETABLE', 'Timetable'), ('CUSTOM', 'Custom')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=220)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=12)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_history', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_history', to='organizations.department')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='organizations.organization')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_history', to='organizations.semester')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Report history',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['organization', 'report_type', 'created_at'], name='reports_rep_organiz_1e957b_idx'), models.Index(fields=['organization', 'generated_by', 'created_at'], name='reports_rep_organiz_a0cc0d_idx'), models.Index(fields=['organization', 'status', 'created_at'], name='reports_rep_organiz_0c4d33_idx'), models.Index(fields=['organization', 'branch', 'department', 'report_type'], name='reports_rep_organiz_4a9e47_idx')],
            },
        ),
    ]
