# Generated by Django 4.2.30 on 2026-06-03 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_schema_rbac_hod_reports'),
        ('organizations', '0002_department_management_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='role_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='authentication.role'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('HOD', 'Head of Department'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'role', 'is_active'], name='organizatio_organiz_b3d0b8_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'organization', 'is_active'], name='organizatio_user_id_b7f121_idx'),
        ),
    ]
