# Generated by Django 4.2.30 on 2026-06-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_schema_rbac_hod_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='geofence_radius',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
